### ISSUE TITLE
NullPointerException in WakefulIntentService

### ISSUE THREAD

**Issue by konklone** [konklone/congress-android#451]
NullPointerException in a parcel. It's in v3.0 of the app, but I don't think anything changed in the WakefulIntentService in 3.1.

java.lang.NullPointerException
at android.os.Parcel.readException(Parcel.java:1328)
at android.os.Parcel.readException(Parcel.java:1276)
at android.net.wifi.IWifiManager$Stub$Proxy.releaseWifiLock(IWifiManager.java:1159)
at android.net.wifi.WifiManager$WifiLock.release(WifiManager.java:1026)
at com.commonsware.cwac.wakeful.WakefulIntentService.onHandleIntent(WakefulIntentService.java:97)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:143)
at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by followztx** [comment]
07-10 09:52:01.941: E/AndroidRuntime(20648): Caused by: java.lang.NullPointerException
07-10 09:52:01.941: E/AndroidRuntime(20648): 	at android.os.Parcel.readException(Parcel.java:1478)
07-10 09:52:01.941: E/AndroidRuntime(20648): 	at android.os.Parcel.readException(Parcel.java:1426)
07-10 09:52:01.941: E/AndroidRuntime(20648): 	at android.net.wifi.IWifiManager$Stub$Proxy.getScanResults(IWifiManager.java:709)
07-10 09:52:01.941: E/AndroidRuntime(20648): 	at android.net.wifi.WifiManager.getScanResults(WifiManager.java:912)

**Comment by followztx** [comment]
解决了没有？

**Comment by konklone** [comment]
Unfortunately, it's simply been too long, and I no longer recall the problem or the solution, or whether it was solved at all.

> 不幸的是，它只是太漫长了，我不再想起这个问题或者解决方案，或者它是否解决了所有。

**Comment by followztx** [comment]
thanks
